SELECT format(
    'CREATE ROLE fitness_app LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD %L',
    :'fitness_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fitness_app')
\gexec

SELECT format(
    'CREATE ROLE agent_app LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD %L',
    :'agent_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'agent_app')
\gexec

ALTER ROLE fitness_app LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
    PASSWORD :'fitness_password';
ALTER ROLE agent_app LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
    PASSWORD :'agent_password';

REVOKE ALL ON DATABASE happy_agent FROM PUBLIC;
GRANT CONNECT ON DATABASE happy_agent TO fitness_app;
GRANT CONNECT ON DATABASE happy_agent TO agent_app;
