import { useEffect, useState, type FormEvent } from 'react';
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { Bot, BookOpen, ChevronRight, Dumbbell, Home, Play, Send, Sparkles, UserRound, X } from 'lucide-react';
import { ApiError, api } from './api';
import './app.css';

type Exercise = { id: string; name: string; sets?: number; reps?: number; category?: string; summary?: string; steps?: string[]; mistakes?: string[]; voiceCue?: string };
type Dashboard = { user: { username: string; preferences?: { trainingDays?: number; style?: string } }; goal?: { id: string; currentWeight: number; targetWeight: number; progress: number; deadline?: string }; bodyRecords?: { weight: number }[]; meals?: { name: string; calories?: number; mealType?: string }[]; plan?: { id: string; title: string; durationMinutes: number; totalSets: number; exercises: Exercise[] }; exercises?: Exercise[]; report?: { conclusion: string; evidence: string; action: string }; ai?: { configured?: boolean; messages?: { role: string; content: string }[] } };

function errorText(error: unknown) { return error instanceof Error ? error.message : '网络似乎出了点问题，请重试。'; }

function AppShell({ data, reload }: { data: Dashboard; reload: () => Promise<void> }) {
  return <div className="desktop"><main className="phone" aria-label="Happy Agent Platform"><Routes>
    <Route path="/" element={<HomePage data={data} reload={reload} />} />
    <Route path="/plan" element={<PlanPage data={data} />} />
    <Route path="/ai" element={<AiPage data={data} />} />
    <Route path="/library" element={<LibraryPage data={data} />} />
    <Route path="/me" element={<MePage data={data} />} />
    <Route path="*" element={<HomePage data={data} reload={reload} />} />
  </Routes><Navigation /></main></div>;
}

function Header({ username, title = '今天，慢慢变好' }: { username: string; title?: string }) { return <div className="topline"><div className="avatar">{username.slice(0, 1)}</div><div><p className="eyebrow">PRIVATE FITNESS LOG</p><h1>{title}</h1></div><div className="icon"><Sparkles size={18} /></div></div>; }

function HomePage({ data, reload }: { data: Dashboard; reload: () => Promise<void> }) {
  const [drawer, setDrawer] = useState(false); const navigate = useNavigate(); const goal = data.goal;
  return <section className="page"><Header username={data.user.username} />
    {goal ? <section className="goal-card"><div className="row"><span>当前体重</span><span className="meta">目标 {goal.targetWeight} kg</span></div><div className="weight">{goal.currentWeight}<small> kg</small></div><div className="progress"><i style={{ width: `${goal.progress}%` }} /></div><div className="row"><span className="meta">已完成 {goal.progress}%</span><button className="detail-link" onClick={() => navigate('/me')}>查看进度详情 <ChevronRight size={15} /></button></div></section> : <Empty text="还没有进行中的目标" action="设定第一个目标" />}
    <div className="quick-grid"><button className="quick orange" onClick={() => navigate('/plan')}>今日训练<small>{data.plan ? `${data.plan.durationMinutes} 分钟 · ${data.plan.totalSets} 组` : '还未安排'}</small></button><button className="quick cream" onClick={() => setDrawer(true)}>今日饮食<small>{data.meals?.length ?? 0} 条已记录</small></button><button className="quick mint" onClick={() => setDrawer(true)}>我要记录<small>身材 / 饮食</small></button><button className="quick blue" onClick={() => navigate('/me#report')}>我的报告<small>看见长期变化</small></button></div>
    <h2 className="section-title">今天的节奏</h2>{data.plan ? <section className="slim-card"><p className="eyebrow">TODAY'S SESSION</p><h3 className="plan-name">{data.plan.title}</h3><p className="meta">{data.plan.exercises.length} 个动作 · {data.plan.totalSets} 组 · {data.plan.durationMinutes} 分钟</p></section> : <Empty text="今天暂时没有训练计划" />}
    {drawer && <RecordDrawer initialWeight={goal?.currentWeight} onClose={() => setDrawer(false)} onSaved={reload} />}
  </section>;
}

function RecordDrawer({ initialWeight, onClose, onSaved }: { initialWeight?: number; onClose: () => void; onSaved: () => Promise<void> }) {
  const [tab, setTab] = useState<'body' | 'meal'>('body'); const [weight, setWeight] = useState(String(initialWeight ?? '')); const [meal, setMeal] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { if (tab === 'body') await api.bodyRecord(Number(weight)); else await api.meal(meal, 0); await onSaved(); onClose(); } catch (err) { setError(errorText(err)); } finally { setSaving(false); } }
  return <div className="drawer-backdrop" role="dialog" aria-label="记录抽屉"><form className="drawer" onSubmit={save}><button type="button" className="quiet" aria-label="关闭记录" onClick={onClose}><X size={18} /></button><div className="handle" /><h2>记录这一刻</h2><div className="tabs"><button type="button" className={tab === 'body' ? 'active' : ''} onClick={() => setTab('body')}>身材记录</button><button type="button" className={tab === 'meal' ? 'active' : ''} onClick={() => setTab('meal')}>饮食记录</button></div>{tab === 'body' ? <label>体重 (kg)<input type="number" step="0.1" value={weight} onChange={(event) => setWeight(event.target.value)} required /></label> : <label>吃了什么<input value={meal} onChange={(event) => setMeal(event.target.value)} placeholder="例如：牛肉面" required /></label>}{error && <p className="error">{error}</p>}<button className="primary" disabled={saving}>{saving ? '正在保存…' : tab === 'body' ? '保存身材记录' : '保存饮食记录'}</button></form></div>;
}

function PlanPage({ data }: { data: Dashboard }) { const [done, setDone] = useState(false); const [error, setError] = useState(''); const plan = data.plan; const exercise = plan?.exercises[0]; async function complete() { if (!plan) return; setError(''); try { await api.completeWorkout(plan.id); setDone(true); if ('vibrate' in navigator) navigator.vibrate?.(100); } catch (err) { setError(errorText(err)); } } function start() { const words = exercise?.voiceCue ?? '开始跟练，注意呼吸与动作稳定。'; if ('speechSynthesis' in window) window.speechSynthesis.speak(new SpeechSynthesisUtterance(words)); else setError(words); if ('vibrate' in navigator) navigator.vibrate?.([50, 40, 50]); }
  if (!plan || !exercise) return <section className="page"><Header username={data.user.username} title="训练计划" /><Empty text="今天还没有可跟练的计划" /></section>;
  return <section className="page"><Header username={data.user.username} title="训练计划" /><section className="card orange"><p className="eyebrow">TODAY · GUIDED</p><h2>{plan.title}</h2><p className="meta">{plan.durationMinutes} 分钟 · {plan.totalSets} 组 · {plan.exercises.length} 个动作</p></section><section className="card"><p className="eyebrow">01 / {plan.exercises.length}</p><h2>{exercise.name}</h2><p className="meta">{exercise.sets ?? 0} 组 × {exercise.reps ?? 0} 次</p><h3>动作步骤</h3>{(exercise.steps ?? []).map((step) => <p className="bullet" key={step}>{step}</p>)}<h3>容易出错</h3>{(exercise.mistakes ?? []).map((mistake) => <p className="bullet" key={mistake}>{mistake}</p>)}</section>{error && <p className="error">{error}</p>}{done ? <p className="notice">已完成，给今天的自己一个赞。</p> : <><button className="primary" onClick={start}><Play size={16} /> 开始跟练</button><button className="quiet" onClick={complete}>完成本次训练</button></>}</section>;
}

function AiPage({ data }: { data: Dashboard }) { const [messages, setMessages] = useState(data.ai?.messages ?? []); const [value, setValue] = useState(''); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const starters = ['今天怎么练', '今晚吃什么', '帮我记一餐', '看看近期状态']; async function submit(message: string) { if (!message.trim()) return; setMessages((list) => [...list, { role: 'user', content: message }]); setValue(''); setSending(true); setError(''); try { await api.aiMessage(message); } catch (err) { setError(err instanceof ApiError && err.status === 503 ? 'AI 服务尚未配置。你仍可以浏览训练、饮食和报告数据。' : errorText(err)); } finally { setSending(false); } }
  return <section className="page"><Header username={data.user.username} title="AI花爷" /><section className="card ai-card"><p className="eyebrow">YOUR STEADY COACH</p><h2>少一点内耗，多一点可执行。</h2><p className="subtle">花爷只给基于你已记录数据的建议。</p></section>{messages.length === 0 && <div className="quick-grid">{starters.map((starter, index) => <button key={starter} className={`quick ${['orange', 'cream', 'mint', 'blue'][index]}`} onClick={() => submit(starter)}>{starter}<small>从这里开始</small></button>)}</div>}{messages.map((message, index) => <section className="card" key={`${message.content}-${index}`}><p className="eyebrow">{message.role === 'user' ? 'YOU' : 'FLOWER COACH'}</p><p>{message.content}</p></section>)}{error && <p className="error">{error}</p>}<div className="fixed-composer"><div className="chips">{['训练安排', '饮食建议', '身体状态'].map((chip) => <button className="chip" key={chip} onClick={() => setValue(chip)}>{chip}</button>)}</div><form className="composer" onSubmit={(event) => { event.preventDefault(); void submit(value); }}><input aria-label="问花爷" value={value} onChange={(event) => setValue(event.target.value)} placeholder="说说你现在的状态…" /><button className="send" aria-label="发送" disabled={sending}><Send size={17} /></button></form></div></section>;
}

function LibraryPage({ data }: { data: Dashboard }) { const [picked, setPicked] = useState<Exercise>(); const exercises = data.exercises ?? []; return <section className="page"><Header username={data.user.username} title="动作库" />{picked ? <><button className="quiet" onClick={() => setPicked(undefined)}>← 返回动作库</button><h2>{picked.name}</h2><p className="subtle">{picked.summary ?? picked.category}</p><div className="steps">{[1, 2, 3, 4].map((step) => <div className="step-art" key={step}>动作步骤 {step}<br /><span className="meta">{picked.steps?.[step - 1] ?? '稳定控制身体'}</span></div>)}</div></> : exercises.length ? <><div className="chips">{['全部', ...Array.from(new Set(exercises.map((item) => item.category ?? '基础')))].map((category) => <span className="chip" key={category}>{category}</span>)}</div><div className="quick-grid">{exercises.map((exercise) => <button className="exercise" key={exercise.id} onClick={() => setPicked(exercise)}>{exercise.name}<small>{exercise.category ?? '基础动作'}</small></button>)}</div></> : <Empty text="动作库正在整理中" />}</section>; }

function MePage({ data }: { data: Dashboard }) { const [logoutError, setLogoutError] = useState(''); async function logout() { try { await api.logout(); window.location.assign('/'); } catch (err) { setLogoutError(errorText(err)); } } const report = data.report; return <section className="page"><Header username={data.user.username} title="我的" /><section className="card mint"><p className="eyebrow">{data.user.username}</p><h2>训练配置</h2><p className="subtle">每周 {data.user.preferences?.trainingDays ?? '—'} 次训练</p><p className="subtle">偏好：{data.user.preferences?.style ?? '未设置'}</p></section><section id="report" className="card report-card">{report ? <><p className="eyebrow">当前目标累计报告</p><h2>{report.conclusion}</h2><h3>证据</h3><p className="subtle">{report.evidence}</p><h3>下一步动作</h3><p className="subtle">{report.action}</p></> : <Empty text="当前目标还没有足够记录生成报告" />}</section><section className="card"><h2>历史</h2><p className="subtle">已记录 {data.bodyRecords?.length ?? 0} 次身体数据，{data.meals?.length ?? 0} 餐饮食。</p><h2>AI 风格</h2><p className="subtle">{data.user.preferences?.style ?? '直接、有分寸'}</p></section>{logoutError && <p className="error">{logoutError}</p>}<button className="quiet" onClick={logout}>退出登录</button></section>; }

function Empty({ text, action }: { text: string; action?: string }) { return <div className="slim-card"><p className="subtle">{text}</p>{action && <button className="detail-link">{action}</button>}</div>; }

function Navigation() { const { pathname } = useLocation(); const items = [{ to: '/', label: '首页', icon: Home }, { to: '/plan', label: '计划', icon: Dumbbell }, { to: '/ai', label: 'AI花爷', icon: Bot }, { to: '/library', label: '动作库', icon: BookOpen }, { to: '/me', label: '我的', icon: UserRound }]; return <nav className="bottom-nav">{items.map(({ to, label, icon: Icon }) => <Link key={to} className={`nav-link ${pathname === to ? 'active' : ''}`} to={to}><Icon />{label}</Link>)}</nav>; }

function Login({ onLogin }: { onLogin: () => Promise<void> }) { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(''); try { await api.login(username, password); await onLogin(); } catch (err) { setError(errorText(err)); } finally { setPending(false); } } return <div className="desktop"><main className="phone login"><div className="login-mark"><Dumbbell /></div><p className="eyebrow">HAPPY BODY / DAILY LOG</p><h1>把训练和吃饭，<br />做成自己的节奏。</h1><p className="subtle">登录后开始记录今天。</p><form onSubmit={submit}><label>用户名<input value={username} onChange={(event) => setUsername(event.target.value)} required /></label><label>密码<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={pending}>{pending ? '正在登录…' : '登录'}</button></form></main></div>; }

export function App() { const [data, setData] = useState<Dashboard>(); const [auth, setAuth] = useState<'loading' | 'login' | 'ready' | 'error'>('loading'); const [error, setError] = useState(''); async function load() { setAuth('loading'); setError(''); try { const result = await api.bootstrap(); setData(result as Dashboard); setAuth('ready'); } catch (err) { if (err instanceof ApiError && err.status === 401) setAuth('login'); else { setError(errorText(err)); setAuth('error'); } } } useEffect(() => { void load(); }, []); if (auth === 'loading') return <div className="desktop"><main className="phone status"><div className="spinner" />正在读取你的记录…</main></div>; if (auth === 'login') return <Login onLogin={load} />; if (auth === 'error' || !data) return <div className="desktop"><main className="phone status"><p>{error || '暂时无法加载数据'}</p><button className="primary" onClick={() => void load()}>重新尝试</button></main></div>; return <BrowserRouter><AppShell data={data} reload={load} /></BrowserRouter>; }
